# Generated by Django 5.1.4 on 2025-01-03 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='store.orderitem'),
        ),
    ]
