# Generated by Django 5.1.4 on 2025-01-06 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='store_custo_last_na_e6a359_idx',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
