# Generated by Django 5.1.4 on 2024-12-14 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggeditem',
            name='tag',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='tags.tag'),
        ),
    ]
